### ISSUE TITLE
Need more explanation about microservices

### ISSUE THREAD

**Issue by surkoff-v** [stratospheric-dev/stratospheric#112]
### What can we improve?

Hello, first of all thanks for the great book ,i've just finished. Help me understand how implement some microservices patterns in aws with Spring Boot. When I run microservices on my server I use Spring Cloud. And for service discovery for example  I use  @EnableEurekaServer for server  @EnableDiscoveryClient for client. What I have to use for service discovery and clients in aws? In book I haven't found such explanation. Could you help me may be with some link with explanation. Am I right that in aws I don't need to use Spring Cloud at all? But what I should use instead. 
PS: I sent the same on email

### Version

Latest

**Comment by BjoernKW** [comment]
Hi, thanks for getting in touch. Unfortunately, these specific patterns and microservices in general are beyond the scope of "Stratospheric - From Zero to Production with Spring Boot and AWS".

These links might help you to get started with this subject, though:

https://docs.aws.amazon.com/AmazonECS/latest/developerguide/service-discovery.html
https://docs.aws.amazon.com/whitepapers/latest/microservices-on-aws/service-discovery.html
https://tomgregory.com/how-to-deploy-eureka-into-aws-ecs/

**Comment by surkoff-v** [comment]
Thanks a lot for the links. I think this topic in next edition of the book
would be great. Because nowadays most of the people using clouds for
microservices development.

**Comment by rieckpil** [comment]
There's no need for most of the Spring Cloud projects (except Spring Cloud AWS). For example, service discovery comes out of the box with the ALB (Load Balancer). You can access your microservices with a stable domain name and the load balancer internally "discovers" all your instances.

Also, the Spring Cloud Config server is not needed, as with the AWS Parameter Store or the Secret Manager you can outsource the configuration values.

We recommend to make use of as many cloud services as possible (where it makes sense) to avoid any maintenance efforts for a self hosted Eureka or Spring Cloud Config server.

**Comment by surkoff-v** [comment]
Thanks for the advise. I have found in articles that you colleague sent me that there exists approach for service discovery with Cloud Map. What approach should be used and when, Service discovery ELB (ALB) based or Cloud Map based? Some articles say that Cloud Map based is client side approach and therefor is faster. What is your opinion?

**Comment by rieckpil** [comment]
I've never worked with Cloud Map so far and hence can only vote for ELB :D
