### ISSUE TITLE
create.sh - use of aws-hello-world/reflectoring-hello-world instead of todo-app-v1 

### ISSUE THREAD

**Issue by amoffet** [stratospheric-dev/stratospheric#140]
### What's going wrong and not working?

The book appears to have been modified to use  todo-app-v1 (in ecs-basic/create.sh) as the ServiceName parameter and in the imageUrl.  The source code has not.

It may also be well to point out that the user may need to change the namespace (from stratospheric) in the book and reflectoring in the code.

**Comment by BjoernKW** [comment]
@amoffet Thanks for bringing this up. We'll unify the namespaces with this pull request https://github.com/stratospheric-dev/stratospheric/pull/141
