### ISSUE TITLE
org.postgresql.util.PSQLException: FATAL: password authentication failed for user "stratospheric"

### ISSUE THREAD

**Issue by arroyavesr** [stratospheric-dev/stratospheric#153]
### What's going wrong and not working?

Hello,  i try to run the sample app, docker compose it sis running but i got connections errors with the progress database.
![image](https://user-images.githubusercontent.com/8078463/196979517-0ace1e4b-eafe-4ef7-9a2d-8698b0d4f6e7.png)
![image](https://user-images.githubusercontent.com/8078463/196979637-e4875868-a83b-4d1f-b5eb-cda2fb437a3c.png)
![image](https://user-images.githubusercontent.com/8078463/196979693-549d8dfc-daf4-4cd8-b107-a5e93209fab7.png)

### Expected outcome

my expectacion is succefull conection to the database

**Comment by rieckpil** [comment]
Which application did you try to run? One within the `chapters` folder or the application within `application` (at the root of the project)?

**Comment by rieckpil** [comment]
Can you share the log outcome of running `docker compose up`? I've just tried it locally and for me it works. We also have a [test](https://github.com/stratospheric-dev/stratospheric/blob/main/application/src/test/java/dev/stratospheric/todoapp/DockerComposeEnvironmentVerificationTest.java) in the pipeline that ensures the application can start with the Docker Compose file we provide.

Any chance you have a conflicting Postgres database running locally?

If possible, please share the logs as text and not as a screenshot.

**Comment by arroyavesr** [comment]
Hi 
you were right, the port was in use, the wierd thing , in such case the image of postgre should send a error, all the containers were running.

Thanks for you help

Regards
