### ISSUE TITLE
Improvement - get Cognito userPoolClientSecret directly from the UserPoolClient

### ISSUE THREAD

**Issue by giuliopulina** [stratospheric-dev/stratospheric#169]
### What's going wrong and not working?

[Starting from AWS CDK 2.37.0](https://github.com/aws/aws-cdk/issues/7225#issuecomment-1210466944), it is possible to get the client secret of a UserPoolClient directly, using the following method call that returns a SecretValue:

`userPoolClient.getUserPoolClientSecret()`

So the workaround using _describeUserPoolClient_ is not needed anymore.

**Comment by BjoernKW** [comment]
Thanks a lot for the feedback! We'll fix this in the next release and change the text in the ebook accordingly
