### ISSUE TITLE
Having an issue with creating the first app using CDK.

### ISSUE THREAD

**Issue by basilk27** [stratospheric-dev/stratospheric#188]
### What's going wrong and not working?

When I get on to run the cdk bootstrap command I am get the following error.

cdk bootstrap aws://740757785710/us-east-1                                                               :heavy_check_mark:
 :hourglass_flowing_sand:  Bootstrapping environment aws://740757785710/us-east-1...
Trusted accounts for deployment: (none)
Trusted accounts for lookup: (none)
Using default execution policy of ‘arn:aws:iam::aws:policy/AdministratorAccess’. Pass ‘--cloudformation-execution-policies’ to customize.
CDKToolkit: creating CloudFormation changeset...
10:29:57 PM | CREATE_FAILED        | AWS::S3::Bucket         | StagingBucket
cdk-hnb659fds-assets-740757785710-us-east-1 already exists
 :x:  Environment aws://740757785710/us-east-1 failed bootstrapping: Error: The stack named CDKToolkit failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: cdk-hnb659fds-assets-740757785710-us-east-1 already exists
    at FullCloudFormationDeployment.monitorDeployment (/Users/basilkiwanuka/.nvm/versions/node/v16.15.1/lib/node_modules/aws-cdk/lib/index.js:327:10235)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /Users/basilkiwanuka/.nvm/versions/node/v16.15.1/lib/node_modules/aws-cdk/lib/index.js:332:2104
    at async Promise.all (index 0)
    at async CdkToolkit.bootstrap (/Users/basilkiwanuka/.nvm/versions/node/v16.15.1/lib/node_modules/aws-cdk/lib/index.js:332:1949)
    at async exec4 (/Users/basilkiwanuka/.nvm/versions/node/v16.15.1/lib/node_modules/aws-cdk/lib/index.js:385:51296)
The stack named CDKToolkit failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: cdk-hnb659fds-assets-740757785710-us-east-1 already exists

**Comment by BjoernKW** [comment]
From what I can gather from the error message, for some reason the S3 bucket with `$BUCKET_NAME` from the `create.sh` script already appears to exist. As suggested by the error message, you could either try and delete the bucket from the AWS console or supply a different `$BUCKET_NAME` parameter to the `create.sh` script:

```
BUCKET_NAME=$1

aws cloudformation create-stack \
  --stack-name stratospheric-demo-infrastructure \
  --template-body file://application-infrastructure.yml \
  --profile stratospheric \
  --parameters \
    ParameterKey=BucketName,ParameterValue=$BUCKET_NAME
```

**Comment by rieckpil** [comment]
The described error seems to come from running `cdk bootstrap` to initialize the region for CDK. @basilk27 did you previously already bootstrapped this account/region combination? If so, this needs to be done only once.

You can visit the CloudFormation service UI within the AWS console to check if there's already the `CDKToolkit` available.
