### ISSUE TITLE
Error performing - 1.06 - Deploying a Service Stack with CloudFormation

### ISSUE THREAD

**Issue by basilk27** [stratospheric-dev/stratospheric#206]
### What's going wrong and not working?

[Create_Service02.docx](https://github.com/stratospheric-dev/stratospheric/files/11628867/Create_Service02.docx)

I attached two documents Create_service.doc is the first part and Create-Service02.doc is the second part.

### Expected outcome

[Create_Service.docx](https://github.com/stratospheric-dev/stratospheric/files/11628873/Create_Service.docx)

**Comment by rieckpil** [comment]
Hey @basilk27, please don't attach any documents and paste your question in plain text/Markdown here.
