### ISSUE TITLE
ECS error log when npm run service:deploy

### ISSUE THREAD

**Issue by andsus** [stratospheric-dev/stratospheric#207]
### What's going wrong and not working?

When deploying service:deploy, the task always failed. 
I check the ECS task log and found out the following.
It seems the flywaydb can not connect to postgredb. 
Is there a tip on how to troubleshoot this scenario?

{"timestamp":"2023-06-04T19:36:48.065000+0000","level":"ERROR","logger":"org.springframework.boot.SpringApplication","thread":"main","message":"Application run failed","full_message":"Application run failed\norg.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org\/springframework\/boot\/autoconfigure\/flyway\/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is org.flywaydb.core.internal.exception.FlywaySqlException: Unable to obtain connection from database: The connection attempt failed.\n-------------------------------------------------------------------------\nSQL State : 08001\nError Code : 0\nMessage : The connection attempt failed.\n\n\tat org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1804)\n\tat org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)\n\tat org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)\n\tat org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)\n\tat org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)\n\tat org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)\n\tat org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)\n\tat org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)\n\tat org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)\n\tat org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1154)\n\tat org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:908)\n\tat org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)\n\tat org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147)\n\tat org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734)\n\tat org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)\n\tat org.springframework.boot.SpringApplication.run(SpringApplication.java:308)\n\tat org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)\n\tat org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)\n\tat dev.stratospheric.todoapp.TodoApplication.main(TodoApplication.java:11)\n\tat java.base\/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat java.base\/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)\n\tat java.base\/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)\n\tat java.base\/java.lang.reflect.Method.invoke(Unknown Source)\n\tat org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)\n\tat org.springframework.boot.loader.Launcher.launch(Launcher.java:108)\n\tat org.springframework.boot.loader.Launcher.launch(Launcher.java:58)\n\tat org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)\nCaused by: org.flywaydb.core.internal.exception.FlywaySqlException: Unable to obtain connection from database: The connection attempt failed.\n-------------------------------------------------------------------------\nSQL State : 08001\nError Code : 0\nMessage : The connection attempt failed.\n\n\tat org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:60)\n\tat org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:75)\n\tat org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:147)\n\tat org.flywaydb.core.Flyway.migrate(Flyway.java:124)\n\tat org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:66)\n\tat org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863)\n\tat org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)\n\t... 26 common frames omitted\nCaused by: org.postgresql.util.PSQLException: The connection attempt failed.\n\tat org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:331)\n\tat org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)\n\tat org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:223)\n\tat org.postgresql.Driver.makeConnection(Driver.java:402)\n\tat org.postgresql.Driver.connect(Driver.java:261)\n\tat com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)\n\tat com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)\n\tat com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)\n\tat com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)\n\tat com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)\n\tat com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)\n\tat com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)\n\tat org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:48)\n\t... 32 common frames omitted\nCaused by: java.net.SocketTimeoutException: Connect timed out\n\tat java.base\/sun.nio.ch.NioSocketImpl.timedFinishConnect(Unknown Source)\n\tat java.base\/sun.nio.ch.NioSocketImpl.connect(Unknown Source)\n\tat java.base\/java.net.SocksSocketImpl.connect(Unknown Source)\n\tat java.base\/java.net.Socket.connect(Unknown Source)\n\tat org.postgresql.core.PGStream.createSocket(PGStream.java:241)\n\tat org.postgresql.core.PGStream.<init>(PGStream.java:98)\n\tat org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:109)\n\tat org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:235)\n\t... 44 common frames omitted\n"}

### Expected outcome

npm run service:deploy to complete.

Thanks for the help

**Comment by rieckpil** [comment]
Hey @andsus,

thanks for reaching out. Can you provide more information about your current setup? Did you already create the database successfully and can you see the database in the RDS overview in the AWS management console in the browser?

**Comment by andsus** [comment]
Yes, 
I've npm run database:deploy already. 
staging-todo-app-database is active on us-west-2a

These env variable are available on the ECS task definition on AWS:
SPRING_DATASOURCE_PASSWORD	value ...

SPRING_DATASOURCE_URL	value	
jdbc:postgresql://staging-todo-app-database.c4mk6do5vazm.us-west-2.rds.amazonaws.com:5432/stagingtodoappdatabase

SPRING_DATASOURCE_USERNAME	value	
stagingtodoappdbUser


application.yml:
cloud:
  aws:
    stack:
      auto: false
    region:
      static: us-west-2
    instance:
      data:
        enabled: false
    sns:
      enabled: false

server:
  forward-headers-strategy: framework

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  application:
    name: todo-app

management:
  metrics:
    export:
      cloudwatch:
        enabled: true
        namespace: stratospheric
        step: 1m
    tags:
      environment: ${ENVIRONMENT_NAME}

# configuration of error-handling-spring-boot-starter (https://wimdeblauwe.github.io/error-handling-spring-boot-starter/)
error:
  handling:
    exception-logging: WITH_STACKTRACE

custom:
  invitation-codes: DUKE, HELLO_WORLD, STRATOSPHERIC # TODO: outsource them -> e.g. env variable or database
  sharing-queue: stratospheric-todo-sharing
  external-url: https://app.devops.prime-video.amazon.dev/
  auto-confirm-collaborations: false
  confirm-email-from-address: noreply@devops-prime-video-amazon-dev.awsapps.com
  environment: ${ENVIRONMENT_NAME}

application-aws.yml:
spring:
  security:
    oauth2:
      client:
        registration:
          cognito:
            clientId: ${COGNITO_CLIENT_ID}
            clientSecret: ${COGNITO_CLIENT_SECRET}
            scope: openid, profile, email
            clientName: stratospheric-users-client
        provider:
          cognito:
            issuerUri: ${COGNITO_PROVIDER_URL}

management:
  metrics:
    export:
      cloudwatch:
        enabled: false # disabled to save some $$$ on our monthly AWS bill

custom:
  sharing-queue: ${TODO_SHARING_QUEUE_NAME}
  web-socket-relay-endpoint: ${WEB_SOCKET_RELAY_ENDPOINT}
  web-socket-relay-username: ${WEB_SOCKET_RELAY_USERNAME}
  web-socket-relay-password: ${WEB_SOCKET_RELAY_PASSWORD}
  web-socket-relay-use-ssl: true
  provide-test-todo-controller: false
  use-cognito-as-identity-provider: true
  provide-dynamodb-via-aws: true

**Comment by andsus** [comment]
I found out that the ServiceApp is missing securityGroupIdsToGrantIngressFromEcs.
