### ISSUE TITLE
Tracing User Actions with Amazon DyanomoDB missing initialization

### ISSUE THREAD

**Issue by andsus** [stratospheric-dev/stratospheric#210]
### What's going wrong and not working?

On local development, local-aws-infrastructure.sh has awslocal dynamodb create-table. But I don't see one for AWS deployment. 
On the book there's a AmazonDynamoDbInitializer class, but it's no longer exists on the git repo.
This is error that I see on ECS cluster:
dev.stratospheric.todoapp.tracing.TracingEvent)\ncom.amazonaws.services.dynamodbv2.model.ResourceNotFoundException: Requested resource not found

### Expected outcome

Should aws cli be run on AWS?
awslocal dynamodb create-table \
    --table-name stage-todo-app-breadcrumbs \
    --attribute-definitions AttributeName=id,AttributeType=S \
    --key-schema AttributeName=id,KeyType=HASH \
    --provisioned-throughput ReadCapacityUnits=10,WriteCapacityUnits=10 \

**Comment by rieckpil** [comment]
Could you solve it?

**Comment by andsus** [comment]
Yes, I am able to check the npm run dynamo:deploy task

Thank you
