### ISSUE TITLE
Bug Chapter 10 - The deployment of the ECS Service freeze 

### ISSUE THREAD

**Issue by hjoly2003** [stratospheric-dev/stratospheric#223]
### What's going wrong and not working?

Hi,
when trying to deploy the ECS service, the process never completes. According to the log of the ECS cluster ([staging-ecsCluster.log](https://github.com/stratospheric-dev/stratospheric/files/12160712/staging-ecsCluster.log)), the system could not resolve the environment variable `COGNITO_USER_POOL_LOGOUT_URL` at line 18 of [LogoutSuccessHandlerConfig.java](https://github.com/stratospheric-dev/stratospheric/blob/b6fe2053692519c07eb56adc2344c97d5c49b236/chapters/chapter-10/application/src/main/java/dev/stratospheric/config/LogoutSuccessHandlerConfig.java).

### Expected outcome

A successful deployment of the ECS service.
The reason is that  `COGNITO_USER_POOL_LOGOUT_URL` is never defined in [ServiceApp.java](https://github.com/stratospheric-dev/stratospheric/blob/b6fe2053692519c07eb56adc2344c97d5c49b236/chapters/chapter-10/cdk/src/main/java/dev/stratospheric/todoapp/cdk/ServiceApp.java). It's rather `COGNITO_LOGOUT_URL` that shall be used (see line 98 of ServiceApp#environmentVariables).

**Comment by rieckpil** [comment]
Looks like that something we forogt during a migration, feel free to provide a PR for a fix. As of now, our chapter versions are in maintenace mode as we only actively maintain everything within `applicaiton`.
