### ISSUE TITLE
Readability: The transparent version of the Stratospheric Technical Architecture Image in the README.md is not readable on a dark mode background. Use the non-transparent image instead

### ISSUE THREAD

**Issue by shantdashjian** [stratospheric-dev/stratospheric#237]
**User Story:**
- In order to easily understand the Stratospheric system architecture we will build following the book, the course, or both
- As a learner
- I want to be able to easily view the technical architecture image included in the README.md

**Description:** 
The transparent version of the Stratospheric Technical Architecture image in the READMe.md is not readable for users with a dark mode GitHub settings.

<img width="863" alt="architecture-image-looks-bad" src="https://github.com/stratospheric-dev/stratospheric/assets/2113918/f5a577f7-c383-4689-b301-937af312fbf2">

**Steps to Reproduce:**
1. Login to your GitHub.
2. Make your theme ***dark mode*** by changing it in Settings > Appearance.
3. Visit the stratospheric GitHub repo (this repo).
4. Scroll down to the [section in the README.md where it says "What We're Going to Build](https://github.com/stratospheric-dev/stratospheric#what-were-going-to-build).

**Current Behavior:**
The image is transparent and thus the details of the architecture are not easily visible on a dark mode theme background.

**Expected Behavior:**
The details of the technical architecture should be readable on any background. 

**Fix:**
Use the non-transparent version of the image rather than the transparent one. This will guarantee the image will look good in all modes. I will submit a PR to fix this issue.

**Comment by BjoernKW** [comment]
Thanks a lot for bringing this up and for readily providing a pull request. I've just merged your pull request.

**Comment by shantdashjian** [comment]
> Thanks a lot for bringing this up and for readily providing a pull request. I've just merged your pull request.

You're welcome @BjoernKW.
