### ISSUE TITLE
Let students restart the course and take the quizzes as many times as they like. 

### ISSUE THREAD

**Issue by shantdashjian** [stratospheric-dev/stratospheric#242]
### What can we improve?

I ask that the Restart Course be enabled at all times. I am an adult learner and as a software professional, I am in charge of my learning. I know what learning style works for me. I paid for the course. I can access the videos and the text as many times as I like, but apparently Leanpub or the course creators decided that I can only take each quiz twice and that's it. If I "complete the course", I can no longer go back and test myself on the material. Why? It doesn't hurt anyone. It costs way more to stream the videos and load the text every time I access the course. Let me also take the quizzes as many times as I like. Eliminate this "No. of Attempts" concept. Also, what the heck is "completing" a course about  Spring and AWS. It takes months and years of revisiting this stuff over and over again to actually "learn it". 
<img width="834" alt="Screen Shot 2023-11-12 at 5 38 58 pm" src="https://github.com/stratospheric-dev/stratospheric/assets/2113918/6a1ffcf4-1424-45cf-9cc2-b1355d34886f">

### Version

Revision 1.1 (2023-04-21) 

### Suggested Changes

I ask that the Restart Course be enabled at all times. Remove any limitation on the number of times I take a quiz, or complete the course.

**Comment by thombergs** [comment]
Hi @shantdashjian,

I wasn't aware of such a restriction. I agree that this should not be. I have reached out to Leanpub support because I can't find a setting to change this restriction. Will keep you posted here.

**Comment by BjoernKW** [comment]
@shantdashjian @thombergs I've now changed the number of quiz attempts to unlimited on each individual request and created this pull request for making that setting global as well: https://github.com/stratospheric-dev/stratospheric-course/pull/11

This change should therefore be available with the next version of the course.

**Comment by thombergs** [comment]
@shantdashjian just to be clear: we already published a new version and it should work already. The above PR is just an improvement. Please let us know if it works.

**Comment by shantdashjian** [comment]
<img width="826" alt="Screen Shot 2023-11-15 at 11 12 33 am" src="https://github.com/stratospheric-dev/stratospheric/assets/2113918/3c933fc2-46da-46ea-9ec1-a69073ab0818">
I see no change. It may be because you would also need to enable restarting the course/making that unlimited as well. I also don't see a new version.

**Comment by BjoernKW** [comment]
@shantdashjian Unfortunately, there currently is an error with Leanpub's publishing system that prevents us from setting an infinite number of quiz attempts. Therefore, for the time being, we've set the quiz attempts to 100, which should be plenty enough. I hope this helps with your issue (and an independent, self-directed learning approach in general).

The new course release should be available in a bit.
