### ISSUE TITLE
Add information on required mapping of /

### ISSUE THREAD

**Issue by ryanmcfall** [stratospheric-dev/stratospheric#257]
### What can we improve?

In chapter 5, the book talks about deploying a Spring Boot app using CDK and uses the authors' Todo app as a sample.  I wanted to try this but use my own app in place of the Todo app.  So I replaced the URL to the docker image and tried to build / deploy.

It look me a long time to discover that the load balancing service periodically checks the health of the deployed app by accessing the URL /, and that if this fails enough times, the deployment fails.  My app didn't have a mapping for this URL.  Once I added it, deployment was smooth.

### Version

1.12

### Suggested Changes

Add a note about the requirement for the root URL to be mapped by the application being deployed.  This probably also belongs in the chapter 1 example that uses CloudFormation directly as well.

**Comment by rieckpil** [comment]
Thanks for this finding, we'll adjust the book 👍

**Comment by rieckpil** [comment]
That's indeed not optimal, what I would suggest is to map the health check to the Actuator endpoint (`/actuator/health or info`) to have it consistent across all apps.
