### ISSUE TITLE
micrometer-registry-cloudwatch2 should be used instead of micrometer-registry-cloudwatch?

### ISSUE THREAD

**Issue by giuliopulina** [stratospheric-dev/stratospheric#262]
### What's going wrong and not working?

Hi, 

I'm building a slightly different version of the app following the book and the sample application, and I noticed that, using [_micrometer-registry-cloudwatch_](https://github.com/stratospheric-dev/stratospheric/blob/cdc7a11cc3732f9aa5832ba0acdeffe950d2ac33/application/build.gradle#L40), metrics are not available to Cloudwatch (even if no error is thrown during publication).
I fixed this issue simply replacing the dependency with _micrometer-registry-cloudwatch2_.

### Expected outcome

I think that, as the whole project is based on AWS Java SDK v2, _micrometer-registry-cloudwatch2_ should be used.

**Comment by BjoernKW** [comment]
Thanks for the suggestion. Yes, you're right, _micrometer-registry-cloudwatch2_ should be used instead of _micrometer-registry-cloudwatch_.
