### ISSUE TITLE
Extend discussion of Todo app integration with Spring Boot to mobile app context for Cognito

### ISSUE THREAD

**Issue by ryanmcfall** [stratospheric-dev/stratospheric#263]
### What can we improve?

The discussion in chapter 10 about integrating with Cognito is very helpful when the Todo app is being implemented in Spring via Thymeleaf views.  I'm having a hard time conceptualizing what stays the same and what changes when the UI is a mobile app that's using Spring for its backend services.  I'm using Flutter for Mobile app development, but I don't think that's particularly relevant. 

Adding a section about that to the book in future revisions, or providing pointers to good resources that may be available elsewhere, would be helpful.  Most discussion I've found about mobile / Cognito focuses on Amplify, and it would be nice to have resources in the book that talk about both how to leverage Amplify and how to interact with Cognito from a mobile app without Amplify.

### Version

1.12

**Comment by BjoernKW** [comment]
Thanks for your suggestion. We'll take this into account for a future book release.
