### ISSUE TITLE
Unable to create Cognito App

### ISSUE THREAD

**Issue by ryanmcfall** [stratospheric-dev/stratospheric#266]
### What can we improve?

I am having difficulty using the code in CognitoApp.java to deploy Cognito resources.  Specifically, I am encountering the following error message:
````
staging-imhere-Cognito |  9/14 | 7:30:36 PM | CREATE_FAILED        | AWS::Lambda::Function                
 | cognito/AWS679f53fac002430cb0da5b7982bd2287 (AWS679f53fac002430cb0da5b7982bd22872D164C4C) 
Resource handler returned message: "The runtime parameter of nodejs14.x is no longer supported for creating or updating 
AWS Lambda functions. We recommend you use the new runtime (nodejs20.x) while creating or updating functions. 
(Service: Lambda, Status Code: 400, Request ID: 559877dd-d3d2-4230-9ff2-22eddc8d7da3)" 
(RequestToken: f7321b78-ee01-7dbd-bd43-4a0ff8abcf6c, HandlerErrorCode: InvalidRequest)
````
It's not clear to me what code is trying to create a Lambda function.  I don't see anything in either `CognitoApp.java` or `CognitoStack.java` that stands out to me as doing this.

A Google search for this error message gave me some pointers that perhaps it was an outdated version of the CDK.  But I just updated to the most recent version of CDK 2 (2.130.0 build bd6e5ee) but this didn't help.

I ran into a similar issue with the version of Postgres and was able to find a method call I could make to specify the desired version of Postgres, but can't find anything similar here.

Any ideas?

### Version

latest

**Comment by giuliopulina** [comment]
I think that the lambda is auto-generated to retrieve the client secret from the user pool.

```json
{
  "DescribeCognitoUserPoolClient": {
    "id": "DescribeCognitoUserPoolClient",
    "path": "ApplicationStack/userPoolClient/DescribeCognitoUserPoolClient",
    "children": {
      "Provider": {
        "id": "Provider",
        "path": "ApplicationStack/userPoolClient/DescribeCognitoUserPoolClient/Provider",
        "constructInfo": {
          "fqn": "aws-cdk-lib.aws_lambda.SingletonFunction",
          "version": "2.130.0"
        }
      }
    }
  }
}
```

By the way, did you update the cdk version in the package.json?

**Comment by ryanmcfall** [comment]
@giuliopulina Thanks for the pointer.  Where did that code come from? I have a few guesses but am pretty new to AWS / CDK.

I hadn't updated package.json, but had updated the global version of cdk.  

I just updated the version in package.json and ran `npm update`.  Then I tried to run the Cognito deployment app again, but got the same result.

I do suspect it's related to the creation of the `UserPoolClient` since the error occurs right after this log statement is generated:
````
CREATE_IN_PROGRESS   | AWS::IAM::Policy                      | 
cognito/userPoolClient/DescribeCognitoUserPoolClient/CustomResourcePolicy 
(userPoolClientDescribeCognitoUserPoolClientCustomResourcePolicy05AFFF63) Resource creation Initiated
```` 

Any other ideas?

**Comment by giuliopulina** [comment]
> @giuliopulina Thanks for the pointer. Where did that code come from? I have a few guesses but am pretty new to AWS / CDK.
> 
> I hadn't updated package.json, but had updated the global version of cdk.
> 
> I just updated the version in package.json and ran `npm update`. Then I tried to run the Cognito deployment app again, but got the same result.
> 
> I do suspect it's related to the creation of the `UserPoolClient` since the error occurs right after this log statement is generated:
> 
> ```
> CREATE_IN_PROGRESS   | AWS::IAM::Policy                      | 
> cognito/userPoolClient/DescribeCognitoUserPoolClient/CustomResourcePolicy 
> (userPoolClientDescribeCognitoUserPoolClientCustomResourcePolicy05AFFF63) Resource creation Initiated
> ```
> 
> Any other ideas?

The code that I posted are from the Cloudformation templates generated from the "cdk synth" command, run in my local environment (specifically, tree.json file).
I have built a different version of the Stratospheric application using a different CDK structure, but the core is the same.
Just for my understanding, are you running your npm/cdk command from your local machine or from the CI (Github Actions)?

If, as I imagine are you running the commands from your local environment, I would suggest to try to run the following commands from your cdk folder:

- npm install 
- npm list 
 (output should be like this)
`-- aws-cdk@2.130.0`
- npm run cognito:deploy

**Comment by ryanmcfall** [comment]
Thanks for the explanation on the `cdk synth` output; that was basically what I was thinking was happening.

I'm running the code from my local machine, not a GitHub action.  When I run `npm list`, I get:
````
imhere_server@0.1.0 C:\Users\mcfal\source\imhere\imhere_server_deploy
└── aws-cdk@2.130.0
````

So that seems correct.  

Any other ideas of things to check for?

**Comment by giuliopulina** [comment]
> Thanks for the explanation on the `cdk synth` output; that was basically what I was thinking was happening.
> 
> I'm running the code from my local machine, not a GitHub action. When I run `npm list`, I get:
> 
> ```
> imhere_server@0.1.0 C:\Users\mcfal\source\imhere\imhere_server_deploy
> └── aws-cdk@2.130.0
> ```
> 
> So that seems correct.
> 
> Any other ideas of things to check for?

Unfortunately not many other ideas, without looking at the project :( if you could share it on a Github, that would surely help to figure out the issue.

The only thing that comes into my mind is to try to re-run 'npm bootstrap' with the new CDK because maybe there are some defaults that need to be overridden.

**Comment by ryanmcfall** [comment]
I tried re-running the bootstrap command, with no luck.  At first it didn't want to do anything, so I deleted that stack.  This caused a few problems but I was able to resolve them using the AWS console, and then re-bootstrap the CDK.  Re-running `npm rum cognito:deploy` caused an error at the same location.

My code is hosted on BitBucket rather than GitHub, but I've created a GitHub repo and pushed the code to `git@github.com:ryanmcfall/cdk_deploy.git`.  There's no value for the `accountId` parameter in `ckd.json`; obviously you'd need to change that / pass it on the command line to test anyway.

Any thoughts on this would be greatly appreciated!

**Comment by giuliopulina** [comment]
Ok I think I found the issue:

- your project depends on latest released version of [stratospheric-dev/constructs](https://github.com/stratospheric-dev/cdk-constructs) ([release 0.1.13](https://github.com/stratospheric-dev/cdk-constructs/blob/cdk-constructs-0.1.13)). 
- unfortunately, this version of stratospheric-dev/constructs contains a reference to [aws-cdk version 2.43.1](https://github.com/stratospheric-dev/cdk-constructs/blob/cdk-constructs-0.1.13/pom.xml#L18), that is a very old version and doesn't contain this [commit](https://github.com/aws/aws-cdk/commit/399b6bbdbfbf6440145e6d78e18898aae6261702) that updates the default Node runtime for custom resources to v18.
This is causing the lambda functions to be generated with Node14 runtime, thus making your deployment fail.

I think the cleanest solution is to wait for the maintainers (@thombergs @BjoernKW @rieckpil) to release a new version of the project.
Temporarily, you can checkout the [stratospheric-dev/constructs](https://github.com/stratospheric-dev/cdk-constructs) project locally, upgrade the cdk dependency to 2.130.0 version, build and install it in local maven repo and update your app to use the SNAPSHOT.

I also found a strange thing in cdk-constructs project: the latest release version is 0.1.13, but the current pom.xml version is [0.1.12-SNAPSHOT](https://github.com/stratospheric-dev/cdk-constructs/blob/main/pom.xml#L6): it should be 0.1.14-SNAPSHOT.

**Comment by ryanmcfall** [comment]
@giuliopulina thanks for all your help following up on this.  I will give this a shot and see what I can do.

**Comment by ryanmcfall** [comment]
I can confirm this approach works.:

* Check out the most recent commit to the cdk-construct repo's main branch ([9191b42](https://github.com/stratospheric-dev/cdk-constructs/commit/9191b42ee4b01915ee27bb16c9bdc1de29cd9c91))
*  Make two changes to `pom.xml`:
    * Modify the property `aws-cdk-lib.version` to have the value **2.130.0**
    * Change the `<version>` property to have the value **0.1.14-SNAPSHOT**
* Execute `mvn install` to install that version of the project to my local repository
* Changed the reference to cdk-constructs in my deployment project's `pom.xml` from version 0.1.13 to 0.1.14-SNAPSHOT
* Ran `npm cognito:deploy`

**Comment by BjoernKW** [comment]
Thanks for this discussion and finding a workaround. I'm closing this for now since the issue has been resolved. We'll release a new version of https://github.com/stratospheric-dev/cdk-constructs soon and update to that version.
