### ISSUE TITLE
IAM role relationship diagram improvement

### ISSUE THREAD

**Issue by szantopeter** [stratospheric-dev/stratospheric#269]
### What can we improve?

in chapter "3. Managing Permissions with IAM" there is a diagram for the IAM role entities could be made more expressive

<img width="1561" alt="image" src="https://github.com/stratospheric-dev/stratospheric/assets/69414/a4b2c7f0-f567-417c-be61-1f0870f68bbc">

### Version

latest

### Suggested Changes

- There should be a relationship (arrow) between user and Role to represent that a user can assume roles
- the boxes could contain a short description of the entities
- the relationship types (1 to 1, 1 to many) could be indicated

**Comment by BjoernKW** [comment]
Thanks for your suggestions. This ER diagram has been kept intentionally simple (hence, no cardinalities and descriptions). As for the relationship between users and roles within IAM, see this section, specifically the sentence "It's similar to an IAM user, but isn't associated with a specific person.": https://docs.aws.amazon.com/IAM/latest/UserGuide/id.html#id_iam-roles

I'm not really therefore, if there actually is a relationship between users and roles on the data model level. Hence, I'm closing this issue for now. Please feel free to comment and reopen, though, in case you'd like to discuss this further.

**Comment by szantopeter** [comment]
Strictly speaking it is the role, that would have a pointer in the tust policy to allow the user to assume the role. I was just initially missing the point how the user and role will interact, but if the intention was to keep the diagram simple then it is fine this way too. Thank you anyway for creating this book I find it very useful!
