### ISSUE TITLE
Don't fail the pipeline if Stack is currently in "update in progress"

### ISSUE THREAD

**Issue by rieckpil** [stratospheric-dev/stratospheric#35]
Right now our pipeline fails if we push two commits right after each other as both trigger the GItHub actions workflow to run.

Most of the time the second commit & push then fails because the first push currently updates our AWS infrastructure.

Ideas to fix:

- wait if there is currently a running pipeline
- don't fail if stack is in progress and rather mark it green

**Comment by thombergs** [comment]
I'd rather not mark it green because then we might think it has been deployed.

On the other hand, if we wait, we might run into the GitHub Actions timeout at some point. 

Maybe there is some GitHub Actions magic that we can do. Like queue a separate workflow that does the deployment or something?

**Comment by thombergs** [comment]
https://developer.github.com/v3/repos/deployments/? I'll have a look at that.

**Comment by thombergs** [comment]
or this? https://github.com/marketplace/actions/cancel-previous-workflow-runs

**Comment by thombergs** [comment]
this seems to be more stable: https://github.com/marketplace/actions/cancel-workflow-action

**Comment by rieckpil** [comment]
https://github.com/marketplace/actions/cancel-workflow-action sounds great. The only concern I have is that if CloudFormation is already in the process of starting a new ECS task and awaiting the health signal from ELB, cancelling the workflow at this point will tigger CloudFormation to rollback (I guess), which also takes time and the next run has to wait until the previous run was successfully canceled.
