### ISSUE TITLE
start-dependencies.sh fails on Windows

### ISSUE THREAD

**Issue by ks32849** [stratospheric-dev/stratospheric#36]
When running the script from gitbash on Windows 10 I am getting:
ERROR: for localstack_main  Cannot create container for service localstack: mkdir C:\Program Files\Git\private: Access is denied.

ERROR: for localstack  Cannot create container for service localstack: mkdir C:\Program Files\Git\private: Access is denied.
ERROR: Encountered errors while bringing up the project.

gmerl@DESKTOP-TJ97MJA MINGW64 ~/gitrepo/stratospheric/application (main)

**Comment by thombergs** [comment]
@ks32849 Thanks for the info. To be honest, I'm not sure if we tested with Git Bash. We'll try to reproduce and see if there is a solution for this.

**Comment by rieckpil** [comment]
@BjoernKW do we need the `TMPDIR` for running LocalStack? I assume our current Docker Compose setup is targeting/working only on Linux + MacOS

**Comment by BjoernKW** [comment]
@rieckpil I think we can do without the TMPDIR workaround. I've just tried it on macOS Catalina and it seems to be working with this.

For further reference see this links about the issue for which "TMPDIR=/private$TMPDIR" is the workaround: 

https://bitbucket.org/atlassian/localstack/issues/40/getting-mounts-failed-on-docker-compose-up
https://github.com/docker/for-mac/issues/1298
https://github.com/docker/for-mac/issues/4247

**Comment by ks32849** [comment]
> @ks32849 Thanks for the info. To be honest, I'm not sure if we tested with Git Bash. We'll try to reproduce and see if there is a solution for this.

I just mentioned the issue because the book actually advises windows users to use either Git Bash or WSL.
(The problem does not occur in WSL by the way.)
