### ISSUE TITLE
Spring Session and OAuth2 Authorization Code Grant flow

### ISSUE THREAD

**Issue by mygordienko** [stratospheric-dev/stratospheric#57]
Hello!

I am currently reading your book and one part sounds wrong to me. Namely, in chapter 10 _Building User Registration and Login with Cognito_ in _Shortcomings when Scaling Out_ section (p. 197) you state that Spring Session would not help with the "redirection to another instance" problem.

I tried to play a bit with the Spring Session to check that out. My test scenario was the following:

Setup:

* Use local OIDC provider (I used Keycloak docker)
* Use simple Spring Boot REST application that just returns OidcUser upon successful login
* Use Spring Session with Redis (Redis running in a separate container)

Steps:

* Launch Keycloak and create a realm, user, client, etc.
* Launch Redis
* Launch the application docker
* Request trigger endpoint via browser (`/oauth2/authorize/keycloak`) and get redirected to the Keycloak login page, but do not enter credentials (at this point we should have Authorization request stored in the dedicated repository)
* Kill the application container (Redis is still running)
* Start the application container again
* Perform login in Keycloak and get redirected back to the application

Result:

OidcUser information is available. 

Without Spring Session the same scenario doesn't work, the application throws an error because it can not find the original _AuthorizationRequest_.

So the whole thing here is in `AuthorizationRequestRepository` (`HttpSessionOAuth2AuthorizationRequestRepository` to be more precise). And I believe Spring Session works in a way that does not alter HttpSessionOAuth2AuthorizationRequestRepository's behavior.

So I conclude that Spring Session with external storage (ex. Redis) can be used in scaling environment along with the OAuth2 Authorization code flow.

**Comment by rieckpil** [comment]
Thanks a lot for your investigation @mygordienko. Indeed the section there is wrong - the `state` information is stored inside the `Session`.  Using Spring Session and storing the session information inside e.g. a relational database, the information is available to all Spring Boot instances.

I made the same investigation with a recent project of mine and will update the corresponding section in the book with the next release. 

Thanks a lot 🚀
