### ISSUE TITLE
Explanation for these argument values

### ISSUE THREAD

**Issue by lealceldeiro** [stratospheric-dev/stratospheric#58]
Hi

Is there a meaning for these three values listed below, or were they just randomly selected by the authors?

*`OUTPUT`* at [`DockerRepositoryApp#L35`](https://github.com/stratospheric-dev/stratospheric/blob/main/cdk/src/main/java/dev/stratospheric/todoapp/cdk/DockerRepositoryApp.java#L35)

    CfnOutput.Builder.create(dockerRepository, "OUTPUT")

*`PUTPUTPUTPUT`* at [`DockerRepositoryApp#L36`](https://github.com/stratospheric-dev/stratospheric/blob/main/cdk/src/main/java/dev/stratospheric/todoapp/cdk/DockerRepositoryApp.java#L36)

      .exportName("PUTPUTPUTPUT")

*`PUT`* at [`DockerRepositoryApp#L37`](https://github.com/stratospheric-dev/stratospheric/blob/main/cdk/src/main/java/dev/stratospheric/todoapp/cdk/DockerRepositoryApp.java#L37)

      .value("PUT")

**Comment by lealceldeiro** [comment]
From the ref docs for [Amazon.CDK.CfnOutput](https://docs.aws.amazon.com/cdk/api/latest/dotnet/api/Amazon.CDK.CfnOutput.html) these arguments don't seem to need any specific values, but I kind of see a patters in the values you selected, and wanted just to confirm.

**Comment by thombergs** [comment]
Hey @lealceldeiro,

thanks for pointing that out! This must have come in through a bad commit when I experimented with Stack output values, but where not using that value anymore, so I just removed it.
