### ISSUE TITLE
Find alternative solution to manual cleaning of "Parameters Stack"

### ISSUE THREAD

**Issue by lealceldeiro** [stratospheric-dev/stratospheric#65]
### What's going wrong and not working?

In the [ServiceApp#L54](https://github.com/stratospheric-dev/stratospheric/blob/d58f2198b86dab3f1f4b1eae6668778b72f877a1/cdk/src/main/java/dev/stratospheric/todoapp/cdk/ServiceApp.java#L54) there's a "Parameters Stack" being constructed as a container for some output parameters: Quoted from the source code:

> // This means that each update will generate a new parameters stack that needs to be cleaned up manually!

While developing solutions such as the _ToDo_ app, deployed to the cloud, I'm looking for solutions that provide the least manual intervention possible.

I think in a production-grade application, which scales up and down as needed and there's a CI/CD flow, we can't possibly expect from anyone to manually clean up any stack created by the deployment pipeline.

I'm a total newbie to cloud development, AWS, and DevOps practices in general, and maybe in this case there's no such alternative, but I'd really love to get rid of this "manual clean up" .... it just feels weird. 

### Expected outcome

To not have to clean up manually the "Parameters Stack" (or any other, for the matter), but to find an alternative solution where the stack (or any similar resource) is automatically cleaned up, or updated if needed.

**Comment by rieckpil** [comment]
Hi @lealceldeiro, sorry for the late response. We put this _issue_ now in our backlog on things to improve.

Indeed the linked GitHub workflow contains our current cleanup solution. It's not perfect but it keeps the CloudFormation stack overview clean :D

For future reference I'll add here the relevant code:
```

    # Each Service stack updates creates a new parameter stack that CloudFormation does not clean up for us.
    # This step deletes all "*Service-Parameters*" stacks except the latest one to keep the house clean.
    - name: Clean up old parameter stacks
      if: github.ref == 'refs/heads/main'
      run: |
        cd cdk
        aws cloudformation describe-stacks --region eu-central-1 --query "Stacks[].StackName" --output text | sed -e "s/\s\+/\n/g" | grep -e "staging-todo-app-Service-Parameters" | sort -r | tail -n+2 > stacks_to_be_deleted.txt
        for stack in $(cat stacks_to_be_deleted.txt); do aws cloudformation delete-stack --stack-name $stack --region eu-central-1;  done
```
