### ISSUE TITLE
Chapter 7 - make GitHub Scripts easier to find

### ISSUE THREAD

**Issue by thombergs** [stratospheric-dev/stratospheric#66]
### What can we improve?

The names of the GitHub scripts are not mentioned in the book which makes them hard to find in the repository. Also, they differ a bit. 

### Version

1.2

### Suggested Changes

Makes the GitHub scripts in the book the same as in the repo and make them easier to find.

**Comment by thombergs** [comment]
We're going to start working on a "Stratospheric" video course soon, and for that we'll create a step-by-step guide and update the book.

**Comment by rieckpil** [comment]
Indeed, the GitHub Actions workflow files that we covered in the eBook were not clearly identifiable. Users had to guess which part is in which `.yaml` file. We'll make it more clear with version 1.6 where we explicitly add the name of the workflow flow. 

The link to the correct folder for the workflows files is presented to the reader at the beginning of the chapter.
