### ISSUE TITLE
`spring-boot-starter-oauth2` should be changed to `spring-boot-starter-oauth2-client`/`server`

### ISSUE THREAD

**Issue by lealceldeiro** [stratospheric-dev/stratospheric#74]
### What can we improve?

In chapter *10. Building User Registration and Login with Amazon Cognito* > item *Using AWS Cognito as an Identity Provider with Spring Security* it is stated:

> The relevant security components are part of the following two Spring Boot starters:
```
dependencies {
  implementation 'org.springframework.boot:spring-boot-starter-security'
  implementation 'org.springframework.boot:spring-boot-starter-oauth2'
}
```

I think `org.springframework.boot:spring-boot-starter-oauth2` is not accurate (or up to date anymore).

In the source code [it's correctly listed](https://github.com/stratospheric-dev/stratospheric/blob/f2a84def267575f76246b99aa7562097d3c6f938/application/build.gradle#L21) as:

`implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'`

### Version

Revision 1.2 (2021-10-24)

### Suggested Changes

Change the code snippet in the mentioned section to:

```
dependencies {
  implementation 'org.springframework.boot:spring-boot-starter-security'
  implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'
}
```

**Comment by BjoernKW** [comment]
Thanks a lot! I've just updated that section. The change will be included in the next ebook update.
