### ISSUE TITLE
Find alternative to storing the cognito client secret as a String parameter

### ISSUE THREAD

**Issue by lealceldeiro** [stratospheric-dev/stratospheric#76]
### What's going wrong and not working?

Currently when the Cognito stack is deployed, the client secret is stored as a string parameter:

https://github.com/stratospheric-dev/stratospheric/blob/7af1161ecba9e1c4455920de414cddcbd9444b92/cdk/src/main/java/dev/stratospheric/todoapp/cdk/CognitoStack.java#L147

This might be a security issue!

I'm aware it's not so straightforward (probably not an option at all) to store a given secret (a value itself) as a *Secret* using AWS SSM, and there has been some discussion about it (see https://github.com/aws/aws-cdk/issues/5810) but I feel there must be at least a workaround to this current approach, which seems insecure to me.

### Expected outcome

A possible solution I can think of right now (I haven't tested it though) is to not store the secret value at all, and have this method (the one to retrieve the secret value) called by whatever code needs it at the very same moment the secret value is needed.

**Comment by BjoernKW** [comment]
Thanks for bringing this up. The rationale behind the decision to use a plaintext string in this example is explained in the section "A Note on Secure Parameters" in the chapter on "Building User Registration and Login with Amazon Cognito".

That section also lists a few options and alternatives for securely storing and retrieving parameters by using the AWS Secrets Manager. See the chapter on "Connecting to a Database with Amazon RDS" for an example of how to use the AWS Secrets Manager.

**Comment by lealceldeiro** [comment]
Thanks @BjoernKW -- I'll dig a bit deeper into how to go with the Spring Cloud AWS Secrets Manager Integration.
