### ISSUE TITLE
Enable local development

### ISSUE THREAD

**Issue by thombergs** [stratospheric-dev/stratospheric#8]
For local development, we need a PostgreSQL database and the AWS Cognito service. 

Create a `docker-compose.yml` that spins up a PostgreSQL database and a Cognito mock with LocalStack.

**Comment by BjoernKW** [comment]
AWS Cognito only seems to be supported in the Pro Edition of LocalStack. See https://github.com/localstack/localstack/issues/26 and https://localstack.cloud/#features

**Comment by rieckpil** [comment]
I guess for this we could go with manually adding e.g. WireMock stubs and mirror the calls that the SDK makes.

But still, I assume with the current setup we _can_ use the production Cognito as we whitelist also http://localhost:8080 as a valid redirect target
