### ISSUE TITLE
Chapter 5 : Getting started with CDK

### ISSUE THREAD

**Issue by ThomasSchmidt81** [stratospheric-dev/stratospheric#93]
### What can we improve?

Page 71: Deploying the generated app:

I followed the previous pages, installed all required stuff and then tried to deploy with "cdk deploy" as the book told me.
But this will fail unless "cdk bootstrap" was used. It creates a couple of resources. This should be explained before the "cdk deploy" part.

❌  CdkHelloAppStack failed: Error: CdkHelloAppStack: SSM parameter /cdk-bootstrap/hnb659fds/version not found. Has the environment been bootstrapped? Please run 'cdk bootstrap' (see https://docs.aws.amazon.com/cdk/latest/guide/bootstrapping.html)
    at CloudFormationDeployments.validateBootstrapStackVersion (/usr/local/lib/node_modules/aws-cdk/lib/api/cloudformation-deployments.ts:521:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
CdkHelloAppStack: SSM parameter /cdk-bootstrap/hnb659fds/version not found. Has the environment been bootstrapped? Please run 'cdk bootstrap' (see https://docs.aws.amazon.com/cdk/latest/guide/bootstrapping.html)

### Version

1.4

### Suggested Changes

Explain "cdk boostrap" and what it does before "cdk deploy"

**Comment by rieckpil** [comment]
Thanks for reporting this issue @ThomasSchmidt81 👍🏻 That's indeed an inconsistency - we'll update the eBook with the next version and add a section for bootstrapping the required CDK resources before deploying anything to AWS.

**Comment by rieckpil** [comment]
Short update: We've adjusted the eBook for more information on the CDK bootstrapping. It will be part of the next release which should arrive next week 👍

**Comment by rieckpil** [comment]
Version 1.6 of the Stratospheric eBook has just been released. We've included a section on bootstrapping an AWS environment and also added a missing GitHub Actions workflow to the book.

Thanks again for your feedback @ThomasSchmidt81. Let us know if you have further questions.

(Closing the issue for now)
